# 当创建新 tag 时时，触发发布流程
name: Publish UdonSharp

on:
  workflow_dispatch:
  push:
    tags:
      - '*'

jobs:
  publish:
    name: Publish UdonSharp
    runs-on: ubuntu-latest
    steps:
      # 加载仓库
      - name: Checkout
        uses: actions/checkout@v3
      # npm 安装
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      # npm 登录
      - name: Publish to UPM
        run: |
          mv Packages/com.vrchat.udonsharp ../com.vrchat.udonsharp
          cd ../com.vrchat.udonsharp
          npm set registry https://upm-packages.dev
          echo "//upm-packages.dev/:_authToken=\${NODE_AUTH_TOKEN}" > .npmrc
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.UPM_TOKEN }}
